In [ ]:
import DistanceBased.similarities as S

ti = S.TI("data/ml-100k",opsional="user-based",toyData=False,k=5)

In [ ]:
# from openpyxl import Workbook

# import the python pandas package
import pandas as pd
 
# create  data_frame1 by creating a dictionary
# in which values are stored as list
data_frame1 = pd.DataFrame({'Fruits': ['Appple', 'Banana', 'Mango',
                                       'Dragon Fruit', 'Musk melon', 'grapes'],
                            'Sales in kg': [21, 30, 15, 10, 50, 40]})
 
# create  data_frame2 by creating a dictionary 
# in which values are stored as list
data_frame2 = pd.DataFrame({'Vegetables': ['tomato', 'Onion', 'ladies finger',
                                           'beans', 'bedroot', 'carrot'],
                            'Sales in kg': [200, 310, 115, 110, 55, 45]})
 
# create  data_frame3 by creating a dictionary 
# in which values are stored as list
data_frame3 = pd.DataFrame({'Baked Items': ['Cakes', 'biscuits', 'muffins',
                                            'Rusk', 'puffs', 'cupcakes'],
                            'Sales in kg': [120, 130, 159, 310, 150, 140]})
 
print(data_frame1)
print(data_frame2)
print(data_frame3)
 
# create a excel writer object
with pd.ExcelWriter("filename.xlsx") as writer:
   
    # use to_excel function and specify the sheet_name and index 
    # to store the dataframe in specified sheet
    data_frame1.to_excel(writer, sheet_name="Fruits", index=False)
    data_frame2.to_excel(writer, sheet_name="Vegetables", index=False)
    data_frame3.to_excel(writer, sheet_name="Baked Items", index=False)

In [2]:
from tqdm import tqdm
from tqdm.contrib.itertools import product

A1 = [i for i in range(1,1000)]
A2 = [i for i in range(1,1000)]
A3 = [i for i in range(1,1000)]

for i in tqdm(A1) :
    a = i

for i,j,k in product(A1,A2,A3) :
    a = i

  2%|▏         | 16384664/997002999 [00:03<03:15, 5020812.21it/s]


KeyboardInterrupt: 

In [ ]:
import pandas as pd
    
old_data = pd.read_excel("filename.xlsx",sheet_name="Vegetables")

In [ ]:
old_data

In [ ]:
basket = {"ring" : []}
balls = ["Volley","Sattle Cock","Foot Ball","Basket Ball"]

for i in balls :
    basket["ring"] += [i]

In [ ]:
import pandas as pd

metadata = {
    "alpa_1": [],
    "alpa_2": [],
    "k": [],
}

alpha_1 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
alpha_2 = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]

k = [5,10,15,18,20,25,30,40,50,100,200]

for a in alpha_1 :
    for b in alpha_2 :
        for c in k :
            metadata["alpa_1"] += [a]
            metadata["alpa_2"] += [b]
            metadata["k"] += [c]


metadata = pd.DataFrame(metadata)

with pd.ExcelWriter("evaluation.xlsx") as writer :
    metadata.to_excel(writer,sheet_name="user-based")

In [ ]:
from MatrixRating import MatrixRating

df = MatrixRating("data/ml-100k")

In [ ]:
df.show_dataset()

In [ ]:
import pandas as pd
import numpy as np
import openpyxl

print(pd.__version__)
print(np.__version__)
print(openpyxl.__version__)

p = None
print(p is not None)

In [ ]:
import numpy as np

# print(1/np.log2(np.arange(2,30+2)))
# dcg = np.array([sum([sum(1/np.log2(np.arange(2,n+2))) for n in range(i)]) for i in range(2,30+2)])
dcg = np.array([sum([sum([1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0][:n]/np.log2(np.arange(2,n+2))) for n in range(i)]) for i in range(2,30+2)])
# print(len(dcg))
print(dcg)
# print(np.array([1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]*dcg))
# print((np.arange(2,4+1)))
# print(list(range(2,4+1)))

In [9]:
import numpy as np
N = 30
gt = np.array([1,1,1,1,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

# IDCG = [sum([sum(1/np.log2(np.arange(2,n+2))) for n in range(i)]) for i in range(2,N+2)]
# DCG = [sum([sum(gt[:n]/np.log2(np.arange(2,n+2))) for n in range(i)]) for i in range(2,N+2)]
DCG = []
for i in range(2,N+2) :
    inner = []
    print(i)
    for n in range(1,i) :
        inner_inner = []
        for n_inner in range(1,n) :
            print((gt[:n_inner]))
            print((1/np.log2(np.arange(3,n+2))))
            # print("==============================")
            dcg_iteration = gt[:n_inner]/np.log2(np.arange(2,n_inner+2))
            # print(dcg_iteration)
            inner_inner.append(gt[n_inner]*sum(dcg_iteration))
            # print("==============================")
            print("inner_inner",gt[n_inner]*sum(dcg_iteration))
            # print("inner",sum(inner_inner))
            # print("==============================")
        inner.append(sum(inner_inner))
    print("inner",sum(inner))
    DCG.append(sum(inner))


# print(np.arange(2,n+1))
# print([(1/np.log2(np.arange(2,n+2))) for n in range(1,2+1)])
# # print([n for n in range(1,1+1)])
# print("DCG",(DCG))
# print("Panjang DCG",len(DCG))
# print("Nilai DCG",sum(DCG))
# print("============")
# print("Panjang IDCG",len(IDCG))
# print("Nilai IDCG",sum(IDCG))
# print("============")
# print(sum(DCG)/sum(IDCG))

2
inner 0
3
[1]
[0.63092975]
inner_inner 1.0
inner 1.0
4
[1]
[0.63092975]
inner_inner 1.0
[1]
[0.63092975 0.5       ]
inner_inner 1.0
[1 1]
[0.63092975 0.5       ]
inner_inner 1.6309297535714575
inner 3.6309297535714578
5
[1]
[0.63092975]
inner_inner 1.0
[1]
[0.63092975 0.5       ]
inner_inner 1.0
[1 1]
[0.63092975 0.5       ]
inner_inner 1.6309297535714575
[1]
[0.63092975 0.5        0.43067656]
inner_inner 1.0
[1 1]
[0.63092975 0.5        0.43067656]
inner_inner 1.6309297535714575
[1 1 1]
[0.63092975 0.5        0.43067656]
inner_inner 2.1309297535714578
inner 8.392789260714373
6
[1]
[0.63092975]
inner_inner 1.0
[1]
[0.63092975 0.5       ]
inner_inner 1.0
[1 1]
[0.63092975 0.5       ]
inner_inner 1.6309297535714575
[1]
[0.63092975 0.5        0.43067656]
inner_inner 1.0
[1 1]
[0.63092975 0.5        0.43067656]
inner_inner 1.6309297535714575
[1 1 1]
[0.63092975 0.5        0.43067656]
inner_inner 2.1309297535714578
[1]
[0.63092975 0.5        0.43067656 0.38685281]
inner_inner 1.0
[1 1]
[0

In [ ]:
import pandas as pd

pd.DataFrame(DCG)

In [16]:
import Evaluation as E

evaluation_toy = E.NDCG([5,14,19,6,11,3,2,10,200,15,17,12,131,89],[2,11,5,6,10,3,14,89,19,200],toyData=True)
print(evaluation_toy.result_evaluation)
print(evaluation_toy.DCG())

0.3536419965282307
732.6582616814859


In [ ]:
print(hasattr(evaluation_toy,"ideal"))

# (evaluation_toy.ideal(30))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           

True


In [10]:
gt = evaluation_toy.groundTruth()
ideal = evaluation_toy.ideal(evaluation_toy.N)

sum([gt_i* ideal_i for gt_i,ideal_i in zip(gt,ideal)][:5])

np.float64(25.9881800171693)

In [ ]:
import Evaluation as E 
import DistanceBased.similarities as S 

ti = S.TI("data/ml-100k",opsional="item-based",alpha_1=0.1,alpha_2=0.4,k=30)

# evaluation = E.Precision("data/ml-100k",ti.get_top_n(),toyData=False)                                                                                                                                                                                                                                                                                                                                                    
# evaluation_ndcg = E.NDCG("data/ml-100k",ti.get_top_n(),toyData=False)

In [9]:
import Evaluation as E

evaluation_recall = E.NDCG("data/ml-100k",ti.get_top_n_array(),toyData=False)

0.045555422398624854
0.02748456036733335
0.022808770737021436
0.01695739120496977
0.017536761791381618


In [14]:
sum(evaluation_recall.result_evaluation)

np.float64(0.026068581299866205)

In [ ]:
print(evaluation_recall.result_evaluation)
# print(evaluation.result_evaluation)
# print(evaluation_toy.result_evaluation)

3.051834064514157e-06


In [7]:
import operator
# ti.get_prediction_array()
user = 120
index = 3
# print(ti.get_top_n_specific_user(user,indexTrain=index))
operator.itemgetter(*ti.get_top_n_specific_user(user,indexTrain=index))(ti.get_prediction_array()[index][user])[:10]

(5.776222581277313,
 5.522307094310257,
 5.353409042590366,
 5.289587148165276,
 5.280314146951142,
 5.158922864026887,
 5.077209594883926,
 5.02712272813693,
 5.016475754657833,
 5.008115797540328)

In [6]:
ti.transformationData(ti.dataset)

item_id,1,2,3,4,5,6,7,8,9,10,...,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682
user_id,,,,,,,,,,,,,,,,,,,,,
1,5.0,3.0,4.0,3.0,3.0,5.0,4.0,1.0,5.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
940,0.0,0.0,0.0,2.0,0.0,0.0,4.0,5.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
941,5.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [1]:
from hybrid import HCF
import DistanceBased.similarities as S

hybrid = HCF("data/ml-100k",S.TI,k_user=20,k_item=30,gamma=0.7,N=20,n=19,alpha_1=0.2,alpha_2=0.5)

cache/tversky_index/user_based/0.2/0.5/tversky_index_similarity.joblib
True
cache/tversky_index/item_based/0.2/0.5/tversky_index_similarity.joblib
False
Train Fold  0
Train Fold  1
Train Fold  2
Train Fold  3
Train Fold  4


In [8]:
from itertools import product

A = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
B = [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]
index = [i for i in range(len(A)*len(B))]

for i in index :
    print("="*33)
    print(i)
    print("="*33)
    print(A[i%11])
    print(B[i%11])

0
0
0
1
0.1
0.1
2
0.2
0.2
3
0.3
0.3
4
0.4
0.4
5
0.5
0.5
6
0.6
0.6
7
0.7
0.7
8
0.8
0.8
9
0.9
0.9
10
1
1
11
0
0
12
0.1
0.1
13
0.2
0.2
14
0.3
0.3
15
0.4
0.4
16
0.5
0.5
17
0.6
0.6
18
0.7
0.7
19
0.8
0.8
20
0.9
0.9
21
1
1
22
0
0
23
0.1
0.1
24
0.2
0.2
25
0.3
0.3
26
0.4
0.4
27
0.5
0.5
28
0.6
0.6
29
0.7
0.7
30
0.8
0.8
31
0.9
0.9
32
1
1
33
0
0
34
0.1
0.1
35
0.2
0.2
36
0.3
0.3
37
0.4
0.4
38
0.5
0.5
39
0.6
0.6
40
0.7
0.7
41
0.8
0.8
42
0.9
0.9
43
1
1
44
0
0
45
0.1
0.1
46
0.2
0.2
47
0.3
0.3
48
0.4
0.4
49
0.5
0.5
50
0.6
0.6
51
0.7
0.7
52
0.8
0.8
53
0.9
0.9
54
1
1
55
0
0
56
0.1
0.1
57
0.2
0.2
58
0.3
0.3
59
0.4
0.4
60
0.5
0.5
61
0.6
0.6
62
0.7
0.7
63
0.8
0.8
64
0.9
0.9
65
1
1
66
0
0
67
0.1
0.1
68
0.2
0.2
69
0.3
0.3
70
0.4
0.4
71
0.5
0.5
72
0.6
0.6
73
0.7
0.7
74
0.8
0.8
75
0.9
0.9
76
1
1
77
0
0
78
0.1
0.1
79
0.2
0.2
80
0.3
0.3
81
0.4
0.4
82
0.5
0.5
83
0.6
0.6
84
0.7
0.7
85
0.8
0.8
86
0.9
0.9
87
1
1
88
0
0
89
0.1
0.1
90
0.2
0.2
91
0.3
0.3
92
0.4
0.4
93
0.5
0.5
94
0.6
0.6
95
0.7
0.7
96
0.8
0.8
97
0.9
0.9


In [7]:
hybrid.get_data_frame(indexFold=1)

,0,1,2,3,4,5,6,7,8,9,...,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681
0,4.191434,3.342502,4.000000,3.000000,3.000000,5.000000,4.000000,4.058240,4.253861,3.000000,...,2.629366,3.815172,2.976833,1.976833,3.359008,1.188996,3.188996,2.188996,3.527014,3.280574
1,3.949932,3.461693,3.348346,3.471906,3.457616,3.949285,4.059022,4.050309,4.332976,4.154132,...,2.873552,3.879511,3.367690,2.367690,3.431325,1.544771,3.544771,2.544771,3.610160,3.309858
2,3.228325,2.348155,2.571642,2.517664,2.726674,2.646788,2.976937,2.896307,2.995449,3.029724,...,1.624078,2.334647,2.252507,1.252507,2.435551,0.589116,2.589116,1.589116,2.645260,2.380694
3,4.633596,4.102808,4.130313,3.933324,4.215032,4.531519,4.742515,4.135150,4.820432,4.727939,...,3.500665,4.359885,3.922474,2.922474,4.048583,2.315231,4.315231,3.315231,4.098887,3.672258
4,4.000000,3.000000,2.335225,2.810368,2.869460,2.955307,3.581179,3.175528,3.049564,3.284486,...,1.743532,3.019506,2.514963,1.514963,2.606331,0.285946,2.285946,1.285946,2.860872,2.559835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
938,4.660177,4.184613,4.006547,4.210114,4.172886,4.599487,4.173756,4.675805,5.000000,4.560169,...,3.404944,4.422877,3.829610,2.829610,4.098325,2.172596,4.172596,3.172596,4.236547,3.907237
939,3.674196,3.016519,2.777539,2.000000,3.010276,3.288239,4.000000,5.000000,3.000000,3.649862,...,2.350173,3.492129,2.803213,1.803213,3.092083,1.157366,3.157366,2.157366,3.262142,2.769242
940,5.000000,3.581037,3.822366,3.805270,3.810361,4.139830,4.000000,4.342962,4.396107,4.329669,...,3.088324,4.122114,3.552435,2.552435,3.700108,1.791446,3.791446,2.791446,3.816052,3.605465
941,4.670553,3.900227,3.562774,3.858767,3.973476,4.216175,4.438771,4.680978,4.529485,4.518703,...,3.235981,4.248068,3.786041,2.786041,3.848066,1.897672,3.897672,2.897672,4.060819,3.826399
